defaults:
  - algo@rolf: dreamer
  - env: default
  - _self_
  - override hydra/hydra_logging: none
  - override hydra/job_logging: stdout


env:
  id: dm.cheetah.run
  screen_size: [64, 64]
  action_repeat: 2
  frame_stack: 1
  absorbing_state: false
  pixel_ob: true
  state_ob: false

# Training
seed: 0
is_train: true
init_ckpt_path: null
init_ckpt_pretrained: false
gpu: null
precision: 16

# Evaluation
ckpt_num: null
num_eval: 1
record_video: true
record_video_caption: true
record_demo: false

# Log
run_prefix: null
notes: null
log_root_dir: log
wandb: false
wandb_entity: null
wandb_project: null

# Hydra
hydra:
  output_subdir: null
  run:
    dir: .
